### PR TITLE
Added thumb as a resource type for image files

### PR DESCRIPTION
**Pull request by lmcglohon**
@ndushay

### CODE REVIEW

**Comment by ndushay** [comment]
@peetucket we need this change in SW for thumbnails of WARC files.  REVS uses this method (https://github.com/sul-dlss/revs-indexer-service/search?utf8=%E2%9C%93&q=image_ids&type=Code ).  Any issues?

o.w. looks good to me.  :+1:

**Comment by ndushay** [comment]
This also impacts spotlight indexing:

https://github.com/sul-dlss/spotlight-indexer-service/blob/master/lib/spotlight_mapper.rb

@cbeer  I can't see any difficulties ... can you?

**Comment by peetucket** [comment]
so i understand this change correctly, it will pull in additional resource types when doing indexing?  but it will not change the behavior unless your objects also have the "thumb" resource and you didn't want it?

if so, then no problem with revs, we have no thumb resources, only image

**Comment by lmcglohon** [comment]
@peetucket you are correct, we are just adding an additional resource type of thumb.

**Pull request merged**
